import { TrackingEvent, Service, Testimonial } from '@/types';

export const services: Service[] = [
  // Vehicle Relocation Pillar (renamed set derived from provided concepts)
  {
    slug: 'single-unit-transport',
    title: 'Individual Vehicle Transport',
    summary: 'Secure, streamlined movement for a single vehicle door-to-door.',
    description: 'End-to-end coordination for personal, auction, or dealership moves with condition capture and reliable ETAs.',
    icon: 'Truck',
    category: 'relocation',
    features: ['Door-to-Door Handling', 'Condition Documentation', 'Live Status Points', 'Verified Carriers'],
    tier: 'standard',
    outcomes: ['Reduced handoff friction', 'Accurate delivery window confidence', 'Protected vehicle condition chain'],
    useCases: ['Auction purchase release', 'Dealership transfer', 'Private sale handover'],
    differentiators: ['Photo & note condition capture workflow', 'Carrier vetting standards', 'Transparent milestone updates'],
    idealCustomers: ['Dealership groups', 'Private sellers', 'Collectors with single moves'],
    kpis: ['On-time pickup adherence focus', 'Damage incident minimization'],
    slaNotes: 'Standard priority scheduling with proactive ETA adjustments.'
  },
  {
    slug: 'fleet-shift',
    title: 'Fleet Shift & Rebalancing',
    summary: 'Coordinated multi-location repositioning for enterprise or rental fleets.',
    description: 'Programmatic scheduling, batching logic, and utilization analytics reduce idle time and empty miles across your footprint.',
    icon: 'MoveRight',
    category: 'relocation',
    features: ['Batch Routing', 'Location Prioritization', 'Utilization Insights', 'Centralized Updates'],
    tier: 'premium',
    outcomes: ['Higher asset utilization', 'Reduced empty reposition miles', 'Centralized reporting transparency'],
    useCases: ['Rental fleet seasonal shift', 'Multi-market availability balancing', 'OEM remarketing flows'],
    differentiators: ['Batch optimization heuristics', 'Prioritized lane sequencing', 'Central dispatch coordination'],
    idealCustomers: ['Rental operators', 'Fleet management platforms', 'OEM distribution'],
    kpis: ['Utilization uplift tracking', 'Reposition cycle time observation'],
    slaNotes: 'Coordinated calendar windows with escalation path for critical assets.',
    ctaLabel: 'Discuss Fleet Program'
  },
  {
    slug: 'premium-enclosed',
    title: 'Protected Enclosed Transport',
    summary: 'Weather-shielded movement for luxury, rare, or high-value units.',
    description: 'Vetted enclosed carriers, soft‑strap securement, and tight chain-of-custody for specialty and collectible vehicles.',
    icon: 'Boxes',
    category: 'relocation',
    features: ['Enclosed Trailers', 'Soft Strap Securement', 'Low Clearance Handling', 'Photo Chain-of-Custody'],
    tier: 'premium',
    outcomes: ['Minimized exposure risk', 'Enhanced asset protection', 'Clear custody traceability'],
    useCases: ['Luxury auction release', 'Exotic vehicle relocation', 'Prototype transport'],
    differentiators: ['Soft-strap handling standards', 'Low-clearance trained carriers', 'Photographic custody log'],
    idealCustomers: ['Collectors', 'Luxury dealerships', 'Specialty brokers'],
    kpis: ['Custody photo completion adherence', 'Incident-free delivery focus'],
    slaNotes: 'Priority scheduling with selective carrier allocation.',
    ctaLabel: 'Request Enclosed Quote'
  },
  {
    slug: 'priority-fastlane',
    title: 'Priority FastLane Moves',
    summary: 'Accelerated routing for time-sensitive transport windows.',
    description: 'Reserved capacity + proactive milestone messaging to meet compressed delivery schedules without guesswork.',
    icon: 'Ship',
    category: 'relocation',
    features: ['Expedited Scheduling', 'Proactive ETA Alerts', 'Capacity Reservation', 'Escalation Path'],
    tier: 'premium',
    outcomes: ['Reduced delivery latency', 'Higher schedule adherence', 'Early risk surfacing'],
    useCases: ['End-of-quarter delivery push', 'Auction clearance deadline', 'Critical retail launch alignment'],
    differentiators: ['Reserved capacity pool', 'Real-time exception signaling', 'Escalation path clarity'],
    idealCustomers: ['Time-critical shippers', 'Auction buyers', 'Performance brokers'],
    kpis: ['Expedited cycle focus', 'Latency variance monitoring'],
    slaNotes: 'Expedited window targeting with proactive incident comms.'
  },
  {
    slug: 'specialty-exotic',
    title: 'Specialty & Exotic Concierge',
    summary: 'White-glove coordination for exotic, custom, or specialty builds.',
    description: 'Enhanced protective handling, confidentiality options, and pre-move planning ensure risk mitigation for unique assets.',
    icon: 'Boxes',
    category: 'relocation',
    features: ['Dedicated Handling', 'Confidential Routing', 'Enhanced Protection', 'Route Risk Review'],
    tier: 'premium',
    outcomes: ['Mitigated exposure & routing risk', 'Confidential identity shielding', 'Predictable handover experience'],
    useCases: ['Confidential prototype move', 'High-profile collection transfer', 'Custom build delivery'],
    differentiators: ['Optional NDA + masked labeling', 'Route risk pre-brief', 'Dedicated handling concierge'],
    idealCustomers: ['Collectors', 'Prototype teams', 'High-net-worth logistics agents'],
    kpis: ['Zero non-authorized disclosure focus', 'Handling compliance checks'],
    slaNotes: 'Concierge scheduling with protective flow controls.'
  },
  {
    slug: 'national-network',
    title: 'National Coverage Network',
    summary: 'Continental U.S. reach with consistent process + visibility.',
    description: 'Unified standards across regions with centralized coordination and integrated tracking for predictable performance.',
    icon: 'MoveRight',
    category: 'relocation',
    features: ['Continental Coverage', 'Unified Standards', 'Central Dispatch', 'Tracking Layer'],
    tier: 'standard',
    outcomes: ['Consistent regional execution', 'Simplified oversight', 'Improved exception containment'],
    useCases: ['Multi-region program onboarding', 'National rollout support', 'Distributed asset availability'],
    differentiators: ['Unified SOP library', 'Centralized dispatch governance', 'Integrative tracking layer'],
    idealCustomers: ['Nationwide fleets', 'Enterprise shippers', 'Program managers'],
    kpis: ['Coverage SLA adherence focus', 'Exception closure tracking'],
    slaNotes: 'Standard national operating cadence with centralized escalation.'
  },
  // Dispatch / Operator Support Pillar
  {
    slug: 'independent-operator-desk',
    title: 'Operator Dispatch Desk',
    summary: 'Day & night dispatch orchestration for independent operators.',
    description: 'Load sourcing, scheduling, and exception handling so operators maximize hours-of-service productivity while we manage complexity.',
    icon: 'Headset',
    category: 'dispatch',
    features: ['Load Sourcing', '24/7 Coordination', 'Exception Handling', 'Carrier Vetting'],
    tier: 'standard',
    outcomes: ['Higher utilization hours', 'Reduced dwell & idle wait time', 'Cleaner exception resolution'],
    useCases: ['Owner-operator lane management', 'Night/weekend coverage gap', 'Scaling new authority operations'],
    differentiators: ['Continuous monitoring window', 'Exception triage protocol', 'Selective load vetting'],
    idealCustomers: ['Owner-operators', 'Small carrier groups', 'New authorities'],
    kpis: ['Dispatch response discipline', 'Exception closure consistency'],
    slaNotes: '24/7 desk coverage with prioritized escalation for safety events.'
  },
  {
    slug: 'live-visibility-suite',
    title: 'Live Visibility Suite',
    summary: 'Real-time milestone + movement intelligence across active loads.',
    description: 'Telematics ingestion and geo-event triggers improve transparency, reduce manual check calls, and surface early-risk signals.',
    icon: 'Truck',
    category: 'dispatch',
    features: ['Geo Events', 'Exception Flags', 'Device Integrations', 'Latency Reduction'],
    tier: 'premium',
    outcomes: ['Lower manual check-call load', 'Earlier disruption detection', 'Improved dwell visibility'],
    useCases: ['High-touch shipper reporting', 'OTIF compliance tracking', 'Temperature-sensitive oversight (future)'],
    differentiators: ['Unified geo-event model', 'Risk flag surfacing', 'Integrative device adapters'],
    idealCustomers: ['Tech-enabled brokers', 'Shippers with SLA dashboards', 'Visibility platform partners'],
    kpis: ['Check-call reduction observation', 'Exception lead time focus'],
    slaNotes: 'Real-time polling intervals with exception push notifications.'
  },
  {
    slug: 'zero-risk-intro',
    title: 'Zero-Risk Pilot Program',
    summary: 'Short trial window to prove value before scaling partnership.',
    description: 'Structured evaluation period with KPI baselines, weekly performance briefs, and no long-term obligation.',
    icon: 'Ship',
    category: 'dispatch',
    features: ['Defined KPIs', 'Weekly Reviews', 'No Obligation', 'Fast Onboarding'],
    tier: 'standard',
    outcomes: ['Faster time-to-proof', 'Lower adoption friction', 'Objective baseline creation'],
    useCases: ['New lane onboarding', 'Dispatch augmentation trial', 'Visibility feature pilot'],
    differentiators: ['Pre-defined success metrics', 'Structured weekly briefing', 'Optional extension path'],
    idealCustomers: ['Mid-market shippers', 'Scaling operators', 'Innovation leads'],
    kpis: ['Baseline variance tracking', 'Adoption velocity focus'],
    slaNotes: 'Pilot governance cadence with weekly alignment call.'
  },
  {
    slug: 'financial-docs-hub',
    title: 'Billing & Settlement Hub',
    summary: 'Streamlined financial packet prep and invoice accuracy control.',
    description: 'Automated document collation, validation checkpoints, and discrepancy flagging accelerate cash cycles.',
    icon: 'Boxes',
    category: 'dispatch',
    features: ['Invoice QA', 'Document Assembly', 'Dispute Reduction', 'Faster Turnaround'],
    tier: 'standard',
    outcomes: ['Reduced billing disputes', 'Shorter DSO trajectory', 'Cleaner documentation trail'],
    useCases: ['High-volume back-office support', 'Rapid invoice collation', 'Settlement variance monitoring'],
    differentiators: ['Structured document validation', 'Discrepancy flag layer', 'Cycle-time visibility'],
    idealCustomers: ['Carrier groups', 'Freight billing teams', 'Third-party admins'],
    kpis: ['Dispute frequency observation', 'Cycle time progression'],
    slaNotes: 'Standard processing targets with variance alerting.'
  },
  {
    slug: 'carrier-standing-score',
    title: 'Performance & Compliance Scoring',
    summary: 'Continuous monitoring of safety, service, and rating indicators.',
    description: 'Composite scoring framework highlights risk trends, enabling proactive remediation and partner optimization.',
    icon: 'Headset',
    category: 'dispatch',
    features: ['Safety Signals', 'On-Time Metrics', 'Trend Dashboards', 'Score Weighting'],
    tier: 'premium',
    outcomes: ['Earlier carrier risk awareness', 'Improved network quality', 'Data-driven partner decisions'],
    useCases: ['Carrier portfolio optimization', 'Compliance program visibility', 'Network refresh planning'],
    differentiators: ['Weighted composite scoring', 'Risk trend surfacing', 'Actionable remediation cues'],
    idealCustomers: ['Brokerage quality teams', 'Compliance managers', 'Network strategy leads'],
    kpis: ['Network score distribution shifts', 'Risk escalation speed focus'],
    slaNotes: 'Periodic refresh cadence with priority alert thresholds.'
  },
  {
    slug: 'regulatory-support-suite',
    title: 'Regulatory Support Suite',
    summary: 'Hands-on assistance with filings, credentials, and audits.',
    description: 'Structured workflow for DOT, IFTA, and record management lowers admin burden and compliance gaps.',
    icon: 'MoveRight',
    category: 'dispatch',
    features: ['IFTA Prep', 'DOT Filing Aid', 'Record Controls', 'Renewal Tracking'],
    tier: 'standard',
    outcomes: ['Reduced filing errors', 'Lower administrative drag', 'Better renewal predictability'],
    useCases: ['New authority support', 'IFTA quarterly cycle prep', 'Pre-audit readiness'],
    differentiators: ['Structured compliance checklist', 'Renewal tracking layer', 'Record hygiene coaching'],
    idealCustomers: ['Growing carriers', 'Owner-operator fleets', 'Compliance officers'],
    kpis: ['Renewal deadline adherence', 'Filing correction minimization'],
    slaNotes: 'Assisted filing cadence with renewal reminders.'
  }
];

export function mockTrackingEvents(trackingNumber: string): TrackingEvent[] {
  const base = Date.now();
  return [
    { id: trackingNumber + '-1', status: 'PENDING', location: 'Order Created', lat: 40.7128, lng: -74.006, timestamp: new Date(base - 1000*60*60*24).toISOString() },
    { id: trackingNumber + '-2', status: 'IN_TRANSIT', location: 'Origin Facility', lat: 39.9526, lng: -75.1652, timestamp: new Date(base - 1000*60*60*18).toISOString() },
    { id: trackingNumber + '-3', status: 'AT_HUB', location: 'Regional Hub', lat: 41.2033, lng: -77.1945, timestamp: new Date(base - 1000*60*60*8).toISOString() },
    { id: trackingNumber + '-4', status: 'OUT_FOR_DELIVERY', location: 'Destination City', lat: 40.4406, lng: -79.9959, timestamp: new Date(base - 1000*60*60*2).toISOString() },
    { id: trackingNumber + '-5', status: 'DELIVERED', location: 'Customer Address', lat: 39.2904, lng: -76.6122, timestamp: new Date(base - 1000*60*30).toISOString() },
  ];
}

export const testimonials: Testimonial[] = [
  { author: 'Alex Rivera', role: 'Supply Chain Director', quote: 'Visibility and reliability improved our on-time performance dramatically.' },
  { author: 'Dana Lee', role: 'E-commerce Ops Lead', quote: 'Seamless integration and consistent delivery speed. Highly recommend.' },
  { author: 'Martin Chen', role: 'Logistics Manager', quote: 'Their tracking transparency reduced our support tickets by 40%.' }
];
